# Generated by Django 3.2.16 on 2023-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about',
            field=models.CharField(default='ss', max_length=999),
            preserve_default=False,
        ),
    ]
