# Generated by Django 3.2.16 on 2023-12-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0002_service_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='about',
            field=models.TextField(max_length=9999),
        ),
    ]
