# Generated by Django 3.2.16 on 2023-12-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0004_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('enable', models.BooleanField(default=True)),
                ('text', models.TextField(max_length=9999)),
                ('position', models.IntegerField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
            ],
        ),
    ]
