# Generated by Django 3.2.16 on 2023-12-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0005_client_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_review',
        ),
    ]
