# Generated by Django 3.2.16 on 2023-12-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0006_delete_client_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=999, null=True),
        ),
    ]
