# Generated by Django 3.2.16 on 2023-12-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0007_service_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
    ]
