# Generated by Django 3.2.16 on 2023-12-25 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0008_rename_name_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('about', models.TextField(max_length=9999)),
                ('Enable', models.BooleanField(default=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
                ('img', models.ImageField(upload_to='svg_images/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process',
            },
        ),
    ]
