# Generated by Django 3.2.16 on 2023-12-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0009_process_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_info',
            name='img',
            field=models.ImageField(upload_to='svg_images/'),
        ),
    ]
