# Generated by Django 3.2.16 on 2024-02-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0011_auto_20240119_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='background',
            field=models.ImageField(default=1, upload_to='Service/bg'),
            preserve_default=False,
        ),
    ]
