# Generated by Django 3.2.16 on 2024-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont_us', '0013_service_thumbnail_white'),
    ]

    operations = [
        migrations.CreateModel(
            name='side_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='side_bar')),
                ('name', models.CharField(max_length=999)),
                ('url', models.CharField(max_length=999)),
            ],
            options={
                'verbose_name': 'side_bar',
                'verbose_name_plural': 'side_bar',
            },
        ),
    ]
