# Generated by Django 3.2.16 on 2023-10-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('heading2', models.CharField(max_length=999)),
                ('enable', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True, unique=True)),
                ('text', models.TextField(max_length=9999)),
                ('IMG', models.ImageField(blank=True, null=True, upload_to='carousel/img1')),
                ('link_lable1', models.CharField(blank=True, max_length=9999, null=True)),
                ('link1', models.CharField(blank=True, max_length=9999, null=True)),
                ('link_lable2', models.CharField(blank=True, max_length=9999, null=True)),
                ('link2', models.CharField(blank=True, max_length=9999, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('enable', models.BooleanField(default=True)),
                ('text', models.TextField(max_length=9999)),
                ('position', models.IntegerField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
            ],
        ),
    ]
