# Generated by Django 3.2.16 on 2023-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_review',
            name='designation',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_review',
            name='name',
            field=models.CharField(default='1', max_length=9999),
            preserve_default=False,
        ),
    ]
