# Generated by Django 3.2.16 on 2023-12-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_employee_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
    ]
