# Generated by Django 3.2.16 on 2024-01-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_employee_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
