# Generated by Django 3.2.16 on 2024-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_carousel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title_1',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='title_2',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
