# Generated by Django 3.2.16 on 2024-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20240310_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='heading2',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
